export const REPORT_DATA = {
    STATUS_INCLUDED:[
        'Pending with Audit',
        'CHRM Registration Done',
        'Agreement created and sent for signature',
        'CP/SC ID in Process',
        'Rejected - Rejected by CHRM OPS',
        'Rejected - Rejected by CHRM Manager',
        'NOC Generated',
        'Executed Agreement sent to CRHM',
        'Pending with CHRM OPS',
        'Rejected by Audit',
        'All missing documents uploaded',
        'Send for Approval',
        'CP/SC ID Generated',
        'Pending with CHRM Manager',
        'Pending with Ashish Parakh',
        ''
    ],
    // STAUS_OWNER_MAP:{
    //     'Pending with Audit':'AUDIT',
    //     'CHRM Registration Done':'CHRM',
    //     'Agreement created and sent for signature':'CHRM',
    //     'CP/SC ID in Process':'CHRM',
    //     'Rejected - Rejected by CHRM OPS':'CHRM',
    //     'Rejected - Rejected by CHRM Manager':'CHRM',
    //     'NOC Generated':'CHRM',
    //     'Executed Agreement sent to CRHM':'CHRM ',
    //     'Pending with CHRM OPS':'CHRM OPS',
    //     'Rejected by Audit':'CHRM OPS',
    //     'All missing documents uploaded':'CHRM OPS',
    //     'Send for Approval':'CHRM OPS',
    //     'CP/SC ID Generated':'CHRM OPS',
    //     'Pending with CHRM Manager':'CHRM TL',
    //     '':'CRRM'
    // },
    DUMMY_DATA:[{
        'Pending with Audit': {Staus: 'Pending with Audit',Status__c: 'Pending with Audit', ownerShip: 'AUDIT', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'CHRM Registration Done': {Staus: 'Broker Registration Done',Status__c: 'CHRM Registration Done', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Agreement created and sent for signature': {Staus: 'Agreement created and sent for signature',Status__c: 'Agreement created and sent for signature', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'CP/SC ID in Process': {Staus: 'Signed Agreement Received - Documents Awaited',Status__c: 'CP/SC ID in Process', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Rejected - Rejected by CHRM OPS': {Staus: 'Rejected by CHRM OPS',Status__c: 'Rejected - Rejected by CHRM OPS', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Rejected - Rejected by CHRM Manager': {Staus: 'Rejected by CHRM Manager',Status__c: 'Rejected - Rejected by CHRM Manager', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'NOC Generated': {Staus: 'NOC Generated',Status__c: 'NOC Generated', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Executed Agreement sent to CRHM': {Staus: 'Executed Agreement sent to CRHM',Status__c: 'Executed Agreement sent to CRHM', ownerShip: 'CHRM ', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Pending with CHRM OPS': {Staus: 'Pending with CHRM OPS',Status__c: 'Pending with CHRM OPS', ownerShip: 'CHRM OPS', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Rejected by Audit': {Staus: 'Rejected by Audit',Status__c: 'Rejected by Audit', ownerShip: 'CHRM OPS', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'All missing documents uploaded': {Staus: 'All missing documents uploaded',Status__c: 'All missing documents uploaded', ownerShip: 'CHRM OPS', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Send for Approval': {Staus: 'Sent for Final Signatures',Status__c: 'Send for Approval', ownerShip: 'CHRM OPS', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'CP/SC ID Generated': {Staus: 'CP/SC ID Generated',Status__c: 'CP/SC ID Generated', ownerShip: 'CHRM OPS', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Pending with CHRM Manager': {Staus: 'Pending with CHRM Manager',Status__c: 'Pending with CHRM Manager', ownerShip: 'CHRM TL', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'Pending with Ashish Parakh': {Staus: 'Pending with Ashish Parakh',Status__c: 'Pending with Ashish Parakh', ownerShip: 'CHRM TL', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0},
        'No_Status': {Status: '',Status__c: '', ownerShip: 'CHRM', noOfDays: 0, days_0_2: 0, days_3_5: 0, days_6_10: 0, moreThan10: 0}
    }]

}