public class X_UnallocatedReceiptRequestWrapper {
    public class X_unallocatedReceiptJSON{
        public String companyCode;	
        public String branchCode;	
        public String projectCode;	
        public String typeOfReceipt; // Default Value : blank	
        public String receiptHeaderRef;
        public String receiptHeaderDate;
        public String bankOrCashAccountNumber;	
        public String receivedFrom;	
        public Decimal receiptAmount;	
        public String sourceCurrencyCode;	
        public String amountInSourceCurrency;	
        public String extRef;	
        public String modeDate;	
        public String modeType;	
        public String modeNo;	
        public String otherType;	
        public String postDated;	
        public Decimal totalAllocationAmount;	
        public String docGuid;
    }
    
    
}